const ERRORS = {
  ERR_LOGIN_FAIL: 'Username or password is incorrect. Please try again',
  ERR_USER_CHANGE_PASSWORD_FAIL: 'Fail to change your password. Please try again',
  ERR_USERNAME_NOT_BLANK: 'Please enter your username.',
  ERR_PASSWORD_NOT_BLANK: 'Please enter your password.',
  ERR_OLD_PASSWORD_NOT_BLANK: 'Please enter your old assword.',
  ERR_NEW_PASSWORD_NOT_BLANK: 'Please enter your new password.',
  ERR_PASSWORD_NOT_MATCH: 'Passwords do not match.',
  ERR_INCORRECT_PASSWORD: 'Password is incorrect',
  ERR_INVALID_DOB: 'User is under 18. Please select a different date',
  ERR_JOINED_DATE_EARLIER_THAN_DOB: 'Joined date is not later than Date of Birth. Please select a different date',
  ERR_JOINED_DATE_WEEKEND: 'Joined date is Saturday or Sunday. Please select a different date',
  ERR_FIRST_NAME_REQUIRED: 'First name is required. Please input a first name',
  ERR_FIRST_NAME_MAX_LENGTH: 'First name not longer than 20',
  ERR_LAST_NAME_MAX_LENGTH: 'Last name not longer than 20',
  ERR_LAST_NAME_REQUIRED: 'Last name is required. Please input a last name',
  ERR_SPECIAL_CHAR_NUMBER: 'This field is not allow special character or number',
  ERR_SPECIAL_CHAR_SPACE_NUMBER: 'This field is not allow special character, number or space',
  ERR_CONVERT_DTO_ENTITY_FAIL: 'Fail to convert your data at server. Please try again',
  ERR_USER_LOGIN_FAIL: 'Username or password is incorrect. Please try again',
  ERR_USER_NOT_FOUND: 'User is not found. Please try another',
  ERR_USER_LOADED_FAIL: 'Fail to load user. Please try again',
  ERR_USER_LIST_NOT_FOUND: 'User list is not found. Please try again',
  ERR_USER_LIST_LOADED_FAIL: 'Fail to load user list. Please try again',
  ERR_USER_INFORMATION_DUPLICATE: 'User information is duplicate. Please try again',
  ERR_CREATE_USER_FAIL: 'Fail to create user {}. Please try again',
  ERR_UPDATE_USER_FAIL: 'Fail to update user {}. Please try again',
  ERR_DELETE_USER_FAIL: 'Fail to delete user {}. Please try again',
  ERR_UPDATE_PASSWORD_USER_FAIL: 'Fail to update user password. Please try again',
  ERR_ROLE_NOT_FOUND: 'Role is not found. Please try another',
  ERR_ROLE_LOADED_FAIL: 'Fail to load user role. Please try again',
  ERR_ROLE_LIST_NOT_FOUND: 'Role list is not found. Please try again',
  ERR_ROLE_LIST_LOADED_FAIL: 'Fail to load role list. Please try again',
  ERR_CATEGORY_NOT_FOUND: 'Category is not found. Please try again',
  ERR_CREATE_CATEGORY_FAIL: 'Fail to create category {}. Please try again',
  ERR_CATEGORY_LIST_LOADED_FAIL: 'Fail to load category list. Please try again',
  ERR_CATEGORY_NAME_EXISTED: 'Category is already existed. Please enter a different category',
  ERR_PREFIX_EXISTED: 'Prefix is already existed. Please enter a different prefix',
  ERR_ASSET_NOT_FOUND: 'Asset is not found. Please try again',
  ERR_ASSET_LOADED_FAIL: 'Fail to load asset {}. Please try again',
  ERR_ASSET_LIST_LOADED_FAIL: 'Fail to load asset list. Please try again',
  ERR_ASSET_NAME_REQUIRED: 'Asset name is required.',
  ERR_ASSET_SPECIFICATION_REQUIRED: 'Specification is required.',
  ERR_CREATE_ASSET_FAIL: 'Fail to create asset {}. Please try again',
  ERR_UPDATE_ASSET_FAIL: 'Fail to update asset {}. Please try again',
  ERR_DELETE_ASSET_FAIL: 'Fail to delete asset {}. Please try again',
  ERR_ASSET_HAVE_BEEN_ASSIGNED: '',
  ERR_ASSET_STATE_NOT_FOUND: 'Asset state is not found. Please try again',
  ERR_ASSET_STATE_LIST_LOADED_FAIL: 'Fail to load asset state list. Please try again',
  ERR_WRONG_OLD_PASSWORD: 'Password is incorrect',
  ERROR_USER_SIGNED_ASSIGMENT: '',
  ERR_ASSIGNMENT_NOT_FOUND: 'Assignment is not found. Please try again',
  ERR_ASSIGNMENT_LOADED_FAIL: 'Fail to load assignment list. Please try again',
  ERR_ASSIGNMENT_LIST_LOADED_FAIL: 'Fail to load assignment list. Please try again',
  ERR_CREATE_ASSIGNMENT_FAIL: 'Fail to create assignment that assigns asset {} to user {}. Please try again',
  ERR_DELETE_ASSIGNMENT_FAIL: 'Fail to delete assignment {}. Please try again',
  ERR_UPDATE_ASSIGNMENT_FAIL: 'Fail to update assignment that assigns asset {} to user {}. Please try again',
  ERR_ACCEPT_ASSIGNMENT_FAIL: 'Fail to accept assignment {}. Please try again.',
  ERR_DECLINE_ASSIGNMENT_FAIL: 'Fail to decline assignment {}. Please try again.',
  ERR_CREATE_REQUEST_FAIL: 'Fail to create returning request for asset {}. Please try again',
  ERR_LOAD_LIST_REQUEST_FAIL: 'Fail to load returning request list. Please try again',
  ERR_REQUEST_LIST_NOT_FOUND: 'Fail to load returning request list. Please try again',
  ERR_RETURN_REQUEST_NOT_FOUND: 'Returning request is not found. Please try again',
  ERR_RETURN_REQUEST_ACCEPT_FAIL: 'Fail to complete returning request for asset. Please try again.',
  ERR_RETURN_REQUEST_CANCEL_FAIL: 'Fail to cancel returning request for asset. Please try again.',
};

export default ERRORS;
