const SUCCESS = {
  USER_LOGIN_SUCCESS: ' Login to the system successful',
  USER_CHANGE_PASSWORD_SUCCESS: 'Your password has been changed successfully',
  USER_LOADED_SUCCESS: 'Load user {} successful',
  USER_CREATED_SUCCESS: 'Create user {} successful',
  USER_UPDATE_SUCCESS: 'Update user {} successful',
  USER_DELETE_SUCCESS: 'Delete user {} successful',
  USER_UPDATE_PASSWORD_SUCCESS: 'Your password is changed successful. Please login to access the system',
  TYPE_LOADED_SUCCESS: 'Load type successful',
  TYPE_LIST_LOADED_SUCCESS: 'Load the list of types successful',
  CATEGORY_LOADED_SUCCESS: 'Load category successful',
  CATEGORY_LIST_LOADED_SUCCESS: 'Load the list of categories successful',
  CATEGORY_CREATED_SUCCESS: 'Create category {} successful',
  ASSET_LOADED_SUCCESS: 'Load asset successful',
  ASSET_LIST_LOADED_SUCCESS: 'Load the list of assets successful',
  ASSET_CREATE_SUCCESS: 'Create asset successful',
  ASSET_UPDATE_SUCCESS: 'Update asset successful',
  ASSET_DELETE_SUCCESS: 'Delete asset successful',
  ASSET_STATE_LIST_LOADED_SUCCESS: 'Load the list of asset states successful',
  ASSIGNMENT_ACCEPT_SUCCESS: 'Accept assignment successful',
  ASSIGNMENT_DECLINE_SUCCESS: 'Decline assignment successful',
  REPORT_LOADED_SUCCESS: 'Load the list of report successful',
  REQUEST_CREATE_SUCCESS: 'Create returning request for asset {} successful',
  REQUEST_LOAD_LIST_SUCCESS: 'Load the list of returning request successful',
  RETURN_REQUEST_ACCEPT_SUCCESS: 'Returning request is completed successful',
  RETURN_REQUEST_CANCEL_SUCCESS: 'Returning request is canceled successful',
};

export default SUCCESS;
